### PR TITLE
Feat: filter undefined symbols. Closes #31

### LINKED ISSUE #31: generate-static-ffi: check for undefined symbol automatically
As I understand, it should be possible to run `get-ffi-obj` and see if a symbol is defined at code generation time, correct? It should then be possible to omit symbols that are undefined.

### PR DESCRIPTION
**Pull request by sorawee**

### CODE REVIEW

**Comment by sorawee** [comment]
@dbenoit17 is this good to merge?

**Comment by sorawee** [comment]
Ping...

**Comment by sorawee** [comment]
Should I continue ping-ing here? It's not urgent, so feel free to merge whenever you want, but I don't want it to be forgotten. Thanks!

**Comment by sorawee** [comment]
It's been almost a year. Is there an update on this?

**Comment by dbenoit17** [comment]
Hi, my apologies that I keep loosing track of this.  I've reviewed and tested this change and it's good to merge.  Thank you for following up to remind me, and thanks very much all of your contributions to this project.

**Pull request merged**
